# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test042601():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_042601(self):
    self.driver.get("https://www.baidu.com/index.php?tn=monline_3_dg")
    self.driver.set_window_size(910, 689)
    self.driver.find_element(By.ID, "kw").click()
    self.driver.find_element(By.ID, "kw").send_keys("假偶天成")
    self.driver.find_element(By.ID, "su").click()
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "假偶天成 (豆瓣) _豆瓣电影").click()
    self.vars["win2802"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win2802"])
    self.driver.execute_script("window.scrollTo(0,2694)")
    self.driver.execute_script("window.scrollTo(0,2945.333251953125)")
    self.driver.find_element(By.ID, "toggle-12424180-copy").click()
    self.driver.execute_script("window.scrollTo(0,3124)")
    self.driver.execute_script("window.scrollTo(0,3316)")
  
